### PR TITLE
fix listening on wrong event

### PR DESCRIPTION
**Pull request by geekdada**
Can't believe this bug has existed for such a long time...

### CODE REVIEW

**Comment by geekdada** [comment]
Hi @chayjay (I really don't know who else to at...), is this project being actively maintained?

**Comment by geekdada** [comment]
Ping @chayjay

**Comment by geekdada** [comment]
Ping @chayjay

**Comment by geekdada** [comment]
Ping @josem

**Comment by josem** [comment]
Hey @geekdada! 

So sorry about this! :pray: And thanks so much for the contribution!

We've fixed this in the main repo last week and we're going to release the change today. //cc @anafilipadealmeida

**Pull request closed without merging**
